server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///springboot?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.88.131
    port: 6379
mybatis:
  type-aliases-package: com.itguigu.pojo

